"""Cloudflare credential setup and verification."""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import webbrowser
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import httpx

from ai_image_indexer.config import DEFAULT_EMBEDDING_MODEL, DEFAULT_VISION_MODEL

WORKERS_AI_SETUP_URL = "https://dash.cloudflare.com/?to=/:account/ai/workers-ai"


def _wrangler_config_paths() -> tuple[Path, ...]:
    home = Path.home()
    return (
        home / ".wrangler" / "config" / "default.toml",
        home / ".config" / ".wrangler" / "config" / "default.toml",
        home / "AppData" / "Roaming" / "xdg.config" / ".wrangler" / "config" / "default.toml",
        home / "AppData" / "Roaming" / ".wrangler" / "config" / "default.toml",
    )


@dataclass(frozen=True)
class CloudflareCredentials:
    account_id: str
    api_token: str
    source: str


class SetupError(Exception):
    pass


def project_env_path(start: Path | None = None) -> Path:
    cwd = (start or Path.cwd()).resolve()
    for directory in (cwd, *cwd.parents):
        candidate = directory / ".env"
        if candidate.exists():
            return candidate
    return cwd / ".env"


def write_env_file(
    env_path: Path,
    account_id: str,
    api_token: str,
    *,
    vision_model: str = DEFAULT_VISION_MODEL,
    embedding_model: str = DEFAULT_EMBEDDING_MODEL,
) -> None:
    lines = [
        "# Cloudflare Workers AI credentials (auto-generated by image-indexer setup)",
        f"CLOUDFLARE_ACCOUNT_ID={account_id}",
        f"CLOUDFLARE_API_TOKEN={api_token}",
        "",
        "# Default AI models (free tier on Cloudflare Workers AI)",
        f"AI_IMAGE_INDEXER_VISION_MODEL={vision_model}",
        f"AI_IMAGE_INDEXER_EMBEDDING_MODEL={embedding_model}",
        "",
    ]
    env_path.write_text("\n".join(lines), encoding="utf-8")


def _parse_wrangler_toml(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def _load_wrangler_credentials() -> CloudflareCredentials | None:
    token = ""
    config_path: Path | None = None

    for path in _wrangler_config_paths():
        if not path.exists():
            continue
        data = _parse_wrangler_toml(path)
        token = data.get("oauth_token") or data.get("api_token") or ""
        account_id = data.get("account_id") or data.get("default_account_id") or ""
        if token and account_id:
            return CloudflareCredentials(
                account_id=account_id,
                api_token=token,
                source=f"wrangler ({path})",
            )
        if token:
            config_path = path
            break

    if not token:
        return None

    try:
        account_id = _wrangler_account_id()
    except (FileNotFoundError, OSError):
        return None
    if not account_id:
        return None

    source = f"wrangler ({config_path})" if config_path else "wrangler login"
    return CloudflareCredentials(account_id=account_id, api_token=token, source=source)


def _wrangler_command() -> list[str]:
    bin_dir = Path.cwd() / "node_modules" / ".bin"
    if os.name == "nt":
        local = bin_dir / "wrangler.cmd"
    else:
        local = bin_dir / "wrangler"
    if local.exists():
        return [str(local)]
    return ["npx", "--yes", "wrangler"]


def _run_wrangler(args: list[str], *, timeout: float = 180.0) -> subprocess.CompletedProcess[str]:
    command = [*_wrangler_command(), *args]
    env = os.environ.copy()
    if not env.get("HTTP_PROXY") and not env.get("HTTPS_PROXY"):
        env.setdefault("HTTP_PROXY", "socks5://127.0.0.1:10808")
        env.setdefault("HTTPS_PROXY", "socks5://127.0.0.1:10808")
    return subprocess.run(
        command,
        capture_output=True,
        text=True,
        timeout=timeout,
        env=env,
        check=False,
        cwd=Path.cwd(),
    )


def _wrangler_account_id() -> str:
    whoami = _run_wrangler(["whoami", "--json"])
    if whoami.returncode != 0:
        return ""
    try:
        whoami_data = json.loads(whoami.stdout)
    except json.JSONDecodeError:
        return ""
    accounts = whoami_data.get("accounts") or []
    if accounts and isinstance(accounts[0], dict):
        return str(accounts[0].get("id") or "").strip()
    return ""


def _load_wrangler_cli_credentials(*, login: bool) -> CloudflareCredentials | None:
    if login:
        login_result = _run_wrangler(["login"])
        if login_result.returncode != 0:
            detail = (login_result.stderr or login_result.stdout or "").strip()
            raise SetupError(f"wrangler login failed: {detail or 'unknown error'}")

    whoami = _run_wrangler(["whoami", "--json"])
    if whoami.returncode != 0:
        return None

    try:
        whoami_data = json.loads(whoami.stdout)
    except json.JSONDecodeError:
        return None

    accounts = whoami_data.get("accounts") or []
    account_id = ""
    if accounts and isinstance(accounts[0], dict):
        account_id = str(accounts[0].get("id") or "").strip()

    token_result = _run_wrangler(["auth", "token", "--json"])
    if token_result.returncode != 0:
        return None

    try:
        token_data = json.loads(token_result.stdout)
    except json.JSONDecodeError:
        return None

    token = str(token_data.get("token") or "").strip()
    if not account_id or not token:
        return None

    return CloudflareCredentials(
        account_id=account_id,
        api_token=token,
        source="wrangler login",
    )


def discover_credentials(*, login: bool = False) -> CloudflareCredentials | None:
    if login or _command_exists("npx") or (Path.cwd() / "node_modules" / ".bin" / "wrangler").exists():
        try:
            creds = _load_wrangler_cli_credentials(login=login)
            if creds:
                return creds
        except (SetupError, subprocess.TimeoutExpired, FileNotFoundError, OSError):
            if login:
                raise

    try:
        return _load_wrangler_credentials()
    except (FileNotFoundError, OSError):
        return None


def _command_exists(name: str) -> bool:
    from shutil import which

    return which(name) is not None


def verify_credentials(
    account_id: str,
    api_token: str,
    *,
    vision_model: str = DEFAULT_VISION_MODEL,
    embedding_model: str = DEFAULT_EMBEDDING_MODEL,
) -> dict[str, Any]:
    headers = {
        "Authorization": f"Bearer {api_token}",
        "Content-Type": "application/json",
    }
    base = f"https://api.cloudflare.com/client/v4/accounts/{account_id}"
    token_status = "unknown"

    with httpx.Client(timeout=60.0, trust_env=False) as client:
        if not api_token.startswith("cfoat_"):
            verify = client.get(f"{base}/tokens/verify", headers=headers)
            verify.raise_for_status()
            verify_body = verify.json()
            if not verify_body.get("success"):
                raise SetupError(f"Token verification failed: {verify_body.get('errors')}")
            token_status = verify_body.get("result", {}).get("status", "unknown")

        embed = client.post(
            f"{base}/ai/run/{embedding_model}",
            headers=headers,
            json={"text": ["image indexer setup test"]},
        )
        if embed.status_code == 401:
            raise SetupError(
                "Cloudflare authentication failed (401). Re-run: image-indexer setup --login"
            )
        embed.raise_for_status()
        embed_body = embed.json()
        if not embed_body.get("success", True):
            raise SetupError(f"Embedding model test failed: {embed_body.get('errors')}")

    return {
        "token_status": token_status,
        "vision_model": vision_model,
        "embedding_model": embedding_model,
    }


def _looks_like_account_id(value: str) -> bool:
    return bool(re.fullmatch(r"[a-f0-9]{32}", value.strip()))


def prompt_for_credentials() -> CloudflareCredentials:
    print("\nCloudflare Workers AI setup")
    print("Dashboard (create token):", WORKERS_AI_SETUP_URL)
    webbrowser.open(WORKERS_AI_SETUP_URL)

    account_id = ""
    while not _looks_like_account_id(account_id):
        account_id = input("\nAccount ID (32 hex chars): ").strip()

    api_token = ""
    while len(api_token) < 20:
        api_token = input("API Token (Workers AI Read + Edit): ").strip()
        if len(api_token) < 20:
            print("Token looks too short. Copy the full token from Cloudflare dashboard.")

    return CloudflareCredentials(
        account_id=account_id,
        api_token=api_token,
        source="manual input",
    )


def run_setup(
    *,
    env_path: Path | None = None,
    login: bool = False,
    verify: bool = True,
    open_browser: bool = True,
) -> Path:
    target = (env_path or project_env_path()).resolve()

    creds = discover_credentials(login=login)
    if creds is None:
        if login:
            raise SetupError(
                "Could not authenticate with wrangler. Install Node.js/npm or enter credentials manually."
            )
        if open_browser and sys.stdin.isatty():
            creds = prompt_for_credentials()
        else:
            raise SetupError(
                "No Cloudflare credentials found. Run: image-indexer setup --login\n"
                "Or create .env with CLOUDFLARE_ACCOUNT_ID and CLOUDFLARE_API_TOKEN."
            )

    if verify:
        verify_credentials(creds.account_id, creds.api_token)

    write_env_file(target, creds.account_id, creds.api_token)
    return target
